@startuml

actor User
participant ServerApplication
participant SceneController
participant ServerChatController
participant Server
participant ClientApplication
participant ClientController
participant Client

User -> ServerApplication: start program
ServerApplication -> ServerChatController: start(main Stage: Stage)
ServerApplication -> SceneController: Scenecontroller(stage: Stage)
ServerChatController -> SceneController:setSceneController(scene Controller: Scene Controller)
ServerChatController -> Server: initialize(url: URL, resourceBundle: ResourceBundle)
ClientApplication -> ClientController: start(main Stage: Stage)
ClientController -> Client: initialize(url: URL, resourceBundle: ResourceBundle)
Client -> Server: sendToServer(message)
Server -> Client: startReadingFromClient(message)
Server -> Client: sendToClient(message)
Client -> Server: startReadingFromClient(message)
ServerChatController -> Server: serverLabel(clientMSG: String, chatHistory: VBox)
ClientController -> Client: clientLabel(serverMessage: String, chatHistory: VBox)  


@enduml
